import {UserStats} from './config';

export const defaultStats: UserStats = {
	schemaVersion: 2,
	name: 'Lukas Parke',
	username: 'LukasParke',
	avatarUrl: 'https://github.com/LukasParke.png',
	bio: null,
	websiteUrl: null,
	location: null,
	generatedAt: '2026-05-29T00:00:00.000Z',
	fetchedAt: 1780012800000,
	isComplete: false,
	summary: {
		totalContributions: 1931,
		currentStreak: 149,
		longestStreak: 149,
		starsReceived: 497,
		forksReceived: 0,
		activeRepos: 0,
		totalRepos: 216,
		languageCount: 55,
		refreshedAt: '2026-05-29T00:00:00.000Z',
	},
	contributions: {
		totalContributions: 1931,
		totalCommits: 1700,
		restrictedContributionsCount: 0,
		currentStreak: 149,
		longestStreak: 149,
		peakDay: null,
		mostProductiveMonth: null,
		calendar: [],
		timeline: [
			{period: '2022', contributions: 140},
			{period: '2023', contributions: 310},
			{period: '2024', contributions: 420},
			{period: '2025', contributions: 610},
			{period: '2026', contributions: 451},
		],
	},
	code: {
		codeByteTotal: 322_400_000,
		linesAdded: 0,
		linesDeleted: 0,
		linesChanged: 0,
		linesOfCodeChanged: 0,
		contributorReposCompleted: 0,
		contributorReposPending: 144,
		contributorReposFailed: 0,
	},
	community: {
		totalPullRequests: 142,
		totalPullRequestReviews: 45,
		openIssues: 0,
		closedIssues: 0,
		repositoriesContributedTo: 0,
		discussionsStarted: 0,
		discussionsAnswered: 0,
		starsGiven: 0,
		followers: 66,
		following: 0,
	},
	repositories: {
		totalRepos: 216,
		publicRepos: 216,
		privateRepos: 0,
		activeRepos: 0,
		archivedRepos: 0,
		forkedRepos: 0,
		originalRepos: 216,
		reposWithStars: 0,
		repoViews: 349,
		repoViewUniques: 0,
		trafficReposCompleted: 0,
		trafficReposPending: 0,
		trafficReposFailed: 0,
		starCount: 497,
		forkCount: 0,
	},
	topLanguages: [
		{languageName: 'TypeScript', color: '#3178c6', value: 112_000_000, percentage: 34.7},
		{languageName: 'Svelte', color: '#ff3e00', value: 67_000_000, percentage: 20.8},
		{languageName: 'Go', color: '#00ADD8', value: 43_000_000, percentage: 13.3},
		{languageName: 'JavaScript', color: '#f1e05a', value: 38_000_000, percentage: 11.8},
		{languageName: 'Python', color: '#3572A5', value: 24_000_000, percentage: 7.4},
	],
	cards: [],
	highlights: [],
	privacy: {
		privateRepositoryDetailsIncluded: false,
		privateCacheDetailsIncluded: false,
		redactedPrivateRepositories: 0,
		redactedRepositoryContributions: 0,
		redactedOptionalMetrics: 0,
	},
	collectionStatus: {
		complete: false,
		coreComplete: true,
		backfillPending: 144,
		backfillCompletedThisRun: 0,
		backfillFailedThisRun: 0,
		warnings: [],
		errors: [],
	},
	repoViews: 349,
	linesOfCodeChanged: 0,
	linesAdded: 0,
	linesDeleted: 0,
	linesChanged: 0,
	totalCommits: 1700,
	totalPullRequests: 142,
	totalPullRequestReviews: 45,
	openIssues: 0,
	closedIssues: 0,
	forkCount: 0,
	starCount: 497,
	totalContributions: 1931,
	codeByteTotal: 322_400_000,
};
